version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:176275544602:task-definition/test-gpd-td:1"
        LoadBalancerInfo:
          ContainerName: "test-gpd-container"
          ContainerPort: "9003"
        PlatformVersion: "LATEST"